### ISSUE TITLE
XMLA Authentication

### ISSUE THREAD

**Issue by yapnel** [bright-sea/webpivottable#6]
Hi

I'm trying to connect to an OLAP server hosted on Oracle cloud that requires authentication. When i entered the XMLA URL and click on Get Cube it is throwing an error "Request failed with status code 401". Does WPT support authentication for OLAP server? Perhaps, i may have missed out something? Kindly please advise

thanks

Nelson

**Comment by bright-sea** [comment]
https://webpivottable.com/doc/options

Set server. basicAuthEnabled To 1 and set server.username and server.password accordingly
